site:
  title: AuroLeap Example Page
  url: https://example.auroleap.org
  # the 404 page and sitemap files only get generated when the url property is set
  start_page: auroleap::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
    edit_url: false
    #snapshot: true
    start_path: AuroLeap
  - url: .
    edit_url: false
    branches: HEAD
    #branches: [main, v2.0, v1.0]
    start_path: Gilbert/docs
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
ui:
  bundle:
    url: ui-bundle
antora:
  extensions:
  - '@antora/lunr-extension'
runtime:
  cache_dir: ./.cache/